version: "3.9"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PASSWORD=admin
        - BUCKET_NAME=practice
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/app